### ISSUE TITLE
 Very beautiful project, but here I still couldn't run

### ISSUE THREAD

**Issue by vitorhugosg** [mtolhuys/laravel-schematics#40]
Hello, how are you?
First of all I want to thank you for the beauty you are doing, it is very good!

But I followed the steps of installing the project, and here it gave this error:

![image](https://user-images.githubusercontent.com/17458174/77457537-9a2b0f00-6ddb-11ea-8efb-c0893c08baa3.png)

If anyone knows how to proceed, please :) thanks in advance.

**Comment by mtolhuys** [comment]
Hi @vitorhugosg,

Thanks for your kind words!

It seems like you're app is having trouble connecting to the database. Did you set it up? If so, is it working in other areas of the application?

**Comment by vitorhugosg** [comment]
I managed here, it was a failure with the connection, I gave a php artisan cache: clear and it worked.

Again a great project, congratulations.


![image](https://user-images.githubusercontent.com/17458174/77464137-7e2c6b00-6de5-11ea-8a35-270a4b4b0194.png)

I've been testing here trying to create my first table, but it turns red like this when I click on create. Do you know how I should proceed?
I'm sorry for the newness.

**Comment by mtolhuys** [comment]
No problem @vitorhugosg, glad you got rid of the connection problem!

The red line you're seeing is because of the model name you are using which is invalid. 

If you want to store models in App\Models you can specify that behavior in the `config/schematics.php` file. You'll see something like this:

```
    'model' => [
        'namespace' => 'App\\',
        'path' => app_path(), <----- This is the path used for creating and editing
        'paths' => [ <----- These paths are scanned for models
            app_path(),
        ],
    ],
```

Also, you can't use underscores or special characters in the model name as they are used as classname.

**Comment by vitorhugosg** [comment]
It worked perfectly, thank you very much and again congratulations for the work;)
